# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ccaacf222c00d0facec545663195a20c"
name = "ledgerxport-prod"
handle = "ledgerxport-prod"
application_url = "https://ledger-xport.vercel.app/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

# [tunnel]
# provider = "ngrok" # (optionnel, souvent inutile en prod)

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_orders,write_orders,read_products,read_customers,read_shopify_payments_payouts,read_shopify_payments_disputes,read_inventory,read_price_rules,read_discounts,read_marketing_events,read_shopify_payments_accounts,read_locales"

[auth]
redirect_urls = [
  "https://ledger-xport.vercel.app/auth/callback",
  "https://ledger-xport.vercel.app/auth/shopify/callback",
  "https://ledger-xport.vercel.app/api/auth/callback"
]

[pos]
embedded = false
